### ISSUE TITLE
How to assess parameter convergence?

### ISSUE THREAD

**Issue by jamesuanhoro** [limengbinggz/ddtlcm#11]
It would be really helpful for users to know how to assess parameter convergence.

Using the example in [the paper](/limengbinggz/ddtlcm/blob/main/JOSS/paper.pdf), it seems something like this works(?)

```r
# incorrect: does not discard burnin
posterior_samples <- t(result_diet$class_probs_samples)
posterior_draws <- posterior::as_draws(posterior_samples)
posterior::summarise_draws(posterior_draws)
bayesplot::mcmc_trace(posterior_draws)
```

It's nice that the content of the results object is described in the manual -- that helped me guess this example. It would be helpful for a reader to see a cleaner version of the above somewhere e.g. in a vignette since convergence assessment is a key part of MCMC.

openjournals/joss-reviews/issues/6220

**Comment by limengbinggz** [comment]
Thank you for pointing this limitation out. We have added a function ``plot.ddt_lcm`` to the package to produce trace plots of model parameters. The users can specify which parameters they are interested in and create a sequence of trace plots of the posterior chain after burn-ins. This function is added in commit [d7621ba](https://github.com/limengbinggz/ddtlcm/commit/d7621bab58d857f58ad59fcf4bf214fed9262588).
